# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\"\x06\n\x04Null\"7\n\x04\x44\x61ta\x12\r\n\x05token\x18\x01 \x01(\t\x12\n\n\x02ID\x18\x02 \x01(\t\x12\x14\n\x0creal_weather\x18\x03 \x01(\r\"\x1e\n\x0c\x43onfirmation\x12\x0e\n\x06succed\x18\x01 \x01(\x08\x32-\n\x07WebBack\x12\"\n\nAddWeather\x12\x05.Data\x1a\r.Confirmationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NULL._serialized_start=16
  _NULL._serialized_end=22
  _DATA._serialized_start=24
  _DATA._serialized_end=79
  _CONFIRMATION._serialized_start=81
  _CONFIRMATION._serialized_end=111
  _WEBBACK._serialized_start=113
  _WEBBACK._serialized_end=158
# @@protoc_insertion_point(module_scope)
