# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import server_pb2 as server__pb2


class WebBackStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddWeather = channel.unary_unary(
            '/WebBack/AddWeather',
            request_serializer=server__pb2.Data.SerializeToString,
            response_deserializer=server__pb2.Confirmation.FromString,
        )


class WebBackServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddWeather(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WebBackServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'AddWeather': grpc.unary_unary_rpc_method_handler(
            servicer.AddWeather,
            request_deserializer=server__pb2.Data.FromString,
            response_serializer=server__pb2.Confirmation.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'WebBack', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))

 # This class is part of an EXPERIMENTAL API.


class WebBack(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddWeather(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/WebBack/AddWeather',
                                             server__pb2.Data.SerializeToString,
                                             server__pb2.Confirmation.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
