name: CI
on:
  push:
    branches:
      - 'HW*'
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: run test
        run: echo 'no test yet'
      - name: format checks
        run: for file in $(find . -iname '*.py'); do diff -u <(cat "$file") <(autopep8 "$file") || exit 1; done
